apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: syf-system
  labels:
    app: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: server
        args:
         - webhook
         - --tlsconf=/run/secrets/tls
        command: ["./server"]
        image: webhook:v1.1
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
        - containerPort: 443
          name: webhook-api
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /run/secrets/tls
          readOnly: true
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: syfwebhook
---
apiVersion: v1
kind: Service
metadata:
  name: syfwebhook
  namespace: syf-system
spec:
  selector:
    app: webhook-server
  ports:
    - port: 443
      targetPort: webhook-api
---